import type { Exam } from "./types";

export const exam2: Exam = {
  id: "farmacologia-avanzada",
  title: "Examen de Farmacología Avanzada",
  description: "100 preguntas · Selección múltiple",
  questions: [
    {
      id: 1,
      question: "Señale lo verdadero con respecto a PEPTIDOS OPIOIDES ENDOGENOS",
      options: [
        "El estímulo de receptores μ se asocia con analgesia supraespinal",
        "El estímulo de receptores μ se asocia con disforia",
        "El estímulo de receptores κ se asocia con euforia",
        "Los receptores delta no tienen localización en medula espinal",
        "Todo lo anterior es correcto",
      ],
      correctAnswer: 0,
    },
    {
      id: 2,
      question: "Señale lo FALSO con respecto a la clasificación de analgésicos",
      options: [
        "ASPIRINA se ubica en grupo 1",
        "DEXTROPROPOXIFENO se ubica en grupo 2",
        "MORFINA se ubica en grupo 3",
        "TRAMADOL se ubica en grupo 2",
        "PARACETAMOL se ubica en el grupo 2",
      ],
      correctAnswer: 4,
    },
    {
      id: 3,
      question: "Señale lo FALSO con respecto al MECANISMO DE ACCION de glucocorticoides",
      options: [
        "Interactúan con receptor intracelular",
        "Interactúan con receptor en el núcleo de las células",
        "Activan la transcripción de genes",
        "Inhiben la transcripción de genes",
        "Inducen síntesis de proteína inhibitoria sobre eicosanoides",
      ],
      correctAnswer: 1,
    },
    {
      id: 4,
      question: "Señale lo FALSO",
      options: [
        "FOSFOLIPASA A2 genera ACIDO ARAQUIDONICO",
        "Ciclooxigenasa genera PGG2 Y PGH2",
        "LIPOCORTINA inhibe a la ciclooxigenasa",
        "Los glucocorticoides reducen la acción de LEUCOTRIENOS",
        "Los glucocorticoides reducen la acción de PROSTAGLANDINAS",
      ],
      correctAnswer: 2,
    },
    {
      id: 5,
      question: "Señale lo FALSO con respecto a las acciones antiinflamatorias de los glucocorticoides",
      options: [
        "Inhiben la producción de IL1",
        "Bloquean la liberación de HISTAMINA",
        "Inducen la síntesis de ICAM-1",
        "Frenan la proliferación de fibroblastos",
        "Bloquean la liberación de IL-6",
      ],
      correctAnswer: 2,
    },
    {
      id: 6,
      question: "Señale lo VERDADERO con respecto a la inflamación",
      options: [
        "La fase aguda se caracteriza por infiltración de leucocitos",
        "La fase subaguda se caracteriza por aumento de permeabilidad capilar",
        "En la fase proliferativa existe tendencia a la fibrosis",
        "La fase catabólica se caracteriza por infiltración de leucocitos",
        "Todo lo anterior es correcto",
      ],
      correctAnswer: 2,
    },
    {
      id: 7,
      question: "Señale lo FALSO con respecto a la inflamación",
      options: [
        "La acción de ciclooxigenasa genera prostaglandinas",
        "La acción de fosfolipasa A2 genera leucotrienos",
        "Los basófilos liberan HISTAMINA",
        "En los gránulos de los mastocitos hay niveles muy elevados de CITOKINAS",
        "La activación del endotelio lleva a la expresión de ELAM",
      ],
      correctAnswer: 3,
    },
    {
      id: 8,
      question: "Señale lo FALSO",
      options: ["C5A es una QUIMIOKINA", "IL-1 es una QUIMIOKINA", "PGE2 es un autacoide", "TNF es una CITOKINA", "LTB4 es una QUIMIOKINA"],
      correctAnswer: 1,
    },
    {
      id: 9,
      question: "Señale lo FALSO con respecto a la acción de los AINES sobre DOLOR Y FIEBRE",
      options: [
        "BRADIQUININA es mediador químico del dolor",
        "HISTAMINA es mediador químico del dolor",
        "La acción antipirética de los AINES depende de su acción antiinflamatoria periférica",
        "PGE2 es mediador químico de la fiebre",
        "Los AINES no producen hipotermia",
      ],
      correctAnswer: 2,
    },
    {
      id: 10,
      question: "Señale lo VERDADERO con respecto a la clasificación de AINES",
      options: [
        "PARACETAMOL es AINE ácido",
        "NIMESULIDA es inhibidor no selectivo de la ciclooxigenasa",
        "ACIDO ACETIL SALICILICO es derivado del ácido acético",
        "MELOXICAM es inhibidor selectivo de la ciclooxigenasa 2",
        "DICLOFENAC es derivado del ácido benzoico",
      ],
      correctAnswer: 3,
    },
    {
      id: 11,
      question: "Señale lo VERDADERO con respecto al ACIDO ACETIL SALICILICO",
      options: [
        "Es inhibidor reversible de la ciclooxigenasa",
        "Su metabolito (ACIDO SALICILICO) es inhibidor no selectivo de la ciclooxigenasa",
        "Su acción antiinflamatoria se manifiesta con dosis de 2g/día",
        "Genera acidosis con dosis menores que las necesarias para producir alcalosis",
        "Sus niveles en sangre de 2mg/ml generan efectos no letales",
      ],
      correctAnswer: 1,
    },
    {
      id: 12,
      question: "Señale lo FALSO con respecto al ACIDO ACETIL SALICILICO",
      options: [
        "Se utiliza como antiinflamatorio en dosis de 500 mg cada 6 horas",
        "Se utiliza como antipirético en dosis de 2g una vez al día",
        "Se utiliza como antitrombótico en dosis de 100mg/día",
        "Se utiliza como antitrombótico en dosis de 200mg/día",
        "Se utiliza en tratamiento de preeclampsia",
      ],
      correctAnswer: 1,
    },
    {
      id: 13,
      question: "Señale lo VERDADERO",
      options: [
        "El sistema microsomal hepático reduce al PARACETAMOL",
        "N-ACETILCISTEINA reduce la dosis tóxica del PARACETAMOL",
        "El metabolito tóxico del PARACETAMOL se conjuga con GLUTATION",
        "FENOBARBITAL incrementa la dosis tóxica del PARACETAMOL",
        "Todo lo anterior es correcto",
      ],
      correctAnswer: 2,
    },
    {
      id: 14,
      question: "Señale lo VERDADERO con respecto al PARACETAMOL",
      options: [
        "Es eficaz como analgésico y antipirético",
        "Posee escasa toxicidad renal",
        "Tiene acción similar sobre las isoformas de la ciclooxigenasa",
        "Se conjuga solamente con ácido glucurónico",
        "Sin tratamiento con inductores enzimáticos, su dosis letal es 10 a 15 g/día",
      ],
      correctAnswer: 0,
    },
    {
      id: 15,
      question: "Señale lo FALSO con respecto al PARACETAMOL",
      options: [
        "Tiene alta biodisponibilidad por vía oral",
        "Alcanza la Cmax en 10 minutos",
        "Su unión a proteínas plasmáticas es 20 a 50%",
        "Su vida media es 2 horas",
        "Se elimina como fármaco metabolizado en el 90 a 100% de la dosis administrada",
      ],
      correctAnswer: 1,
    },
    {
      id: 16,
      question: "Señale lo FALSO con respecto al DICLOFENAC",
      options: [
        "Su vida media es de 6 horas",
        "Puede generar edema",
        "Puede generar efectos sobre el Sistema Nervioso Central",
        "Está indicado en tratamiento de osteoartritis",
        "Es útil en tratamiento del dolor post-operatorio",
      ],
      correctAnswer: 0,
    },
    {
      id: 17,
      question: "Señale lo FALSO",
      options: [
        "El R IBUPROFENO es responsable de la acción antineutrófila",
        "El S IBUPROFENO inhibe a la ciclooxigenasa",
        "Los pacientes con alteraciones visuales por IBUPROFENO deben suspender el tratamiento",
        "Los efectos adversos más frecuentes del IBUPROFENO son alteraciones visuales",
        "La función hepática regula la acción antiinflamatoria del IBUPROFENO",
      ],
      correctAnswer: 3,
    },
    {
      id: 18,
      question: "Señale lo VERDADERO con respecto al IBUPROFENO",
      options: [
        "La dosis es 1200 mg una vez por día",
        "En niños, la dosis es 100 mg/kg/día",
        "La dosis máxima total es 80 mg/kg/día",
        "En artritis reumatoidea la dosis llega a 80 mg/kg/día",
        "En artritis reumatoidea, con peso menor de 30 kg, la dosis máxima es 500 mg/día",
      ],
      correctAnswer: 4,
    },
    {
      id: 19,
      question: "Señale lo FALSO con respecto al PIROXICAM",
      options: [
        "Se utiliza en tratamiento de patología osteoarticular",
        "Inhibe la síntesis de prostaglandinas",
        "Bloquea la acción de neutrófilos",
        "Su vida media es 24 horas",
        "Tiene circulación enterohepática",
      ],
      correctAnswer: 3,
    },
    {
      id: 20,
      question: "Señale lo VERDADERO",
      options: [
        "PIROXICAM se elimina en un 60% por orina",
        "PIROXICAM alcanza el estado de equilibrio en 2 días",
        "La dosis de PIROXICAM es 10 a 20 mg/día",
        "La vida media del MELOXICAM es 48 horas",
        "IBUPROFENO es más seguro y potente que MELOXICAM",
      ],
      correctAnswer: 2,
    },
    {
      id: 21,
      question: "Señale lo VERDADERO con respecto al control farmacológico de la analgesia espinal",
      options: [
        "El neurotransmisor GABA se controla con benzodiacepinas",
        "El neurotransmisor encefalina se controla con pregabalina",
        "El neurotransmisor glutamato se controla con opiáceos",
        "El neurotransmisor 5HT se controla con valproico",
      ],
      correctAnswer: 0,
    },
    {
      id: 22,
      question: "Señale lo FALSO, con respecto a la vía del dolor, a nivel supraespinal",
      options: [
        "La activación del sistema retículo medular genera analgesia",
        "El sistema mesencéfalo medular se origina en la SGP",
        "La activación del sistema cortico medular genera dolor",
        "En la neuromodulación de origen supraespinal participa serotonina",
      ],
      correctAnswer: 2,
    },
    {
      id: 23,
      question: "Señale lo FALSO, con respecto a la clasificación de analgésicos",
      options: ["Aspirina es del GRUPO 1", "Buprenorfina es del GRUPO 2", "Propoxifeno es del GRUPO 2", "Morfina es del GRUPO 3"],
      correctAnswer: 1,
    },
    {
      id: 24,
      question: "Señale lo FALSO, con respecto a la clasificación de epilepsia",
      options: [
        "El GRAN MAL es epilepsia primaria",
        "El PEQUEÑO MAL es epilepsia primaria",
        "Las convulsiones parciales simples pertenecen a epilepsia secundaria",
        "El síndrome de WEST es epilepsia secundaria",
      ],
      correctAnswer: 2,
    },
    {
      id: 25,
      question: "Señale lo VERDADERO, con respecto a la clasificación de drogas antiepilépticas",
      options: [
        "Fenobarbital genera inhibición del canal sodio",
        "Etosuximida genera inhibición del complejo calcio calmodulina",
        "Valproico genera disminución de función GABA",
        "Vigabatrina genera disminución de función GABA",
      ],
      correctAnswer: 1,
    },
    {
      id: 26,
      question: "Señale lo FALSO, con respecto a las indicaciones de drogas antiepilépticas",
      options: [
        "Fenobarbital está indicado en el GRAN MAL",
        "Valproico está indicado en STATUS EPILEPTICO",
        "Clonazepam está indicado en el PEQUEÑO MAL",
        "Clonazepam está indicado en convulsiones mioclónicas",
      ],
      correctAnswer: 1,
    },
    {
      id: 27,
      question: "Señale lo VERDADERO, con respecto a acciones farmacológicas de benzodiacepinas",
      options: ["Son drogas ansiolíticas", "Son drogas sedantes", "Son drogas miorrelajantes", "Todo lo anterior es correcto"],
      correctAnswer: 3,
    },
    {
      id: 28,
      question: "En términos de Índice Terapéutico, ¿cuál de los siguientes parámetros caracteriza al fármaco más seguro?",
      options: ["0,8", "1", "20", "40"],
      correctAnswer: 3,
    },
    {
      id: 29,
      question: "En una emergencia ¿por qué motivo emplearía la administración endovenosa?",
      options: ["Su absorción es rápida", "No se afecta por citocromo P-450", "La biodisponibilidad es del 100%", "Porque el paciente no tolera la vía oral"],
      correctAnswer: 2,
    },
    {
      id: 30,
      question: "¿A qué clase de receptores pertenece el receptor de glucocorticoides?",
      options: ["Metabotrópico", "Asociados a proteína G", "Ionotrópico de sodio", "Citoplasmático"],
      correctAnswer: 3,
    },
    {
      id: 31,
      question: "Un antagonista competitivo puro se caracteriza por:",
      options: [
        "Producir un efecto opuesto al agonista",
        "Impedir la acción del agonista sin poseer eficacia",
        "No requerir la presencia de receptor de reserva",
        "Carecer de afinidad por el receptor",
      ],
      correctAnswer: 1,
    },
    {
      id: 32,
      question: "¿Cuál es el mecanismo de transporte más frecuente por el cual los fármacos son absorbidos?",
      options: ["Difusión simporter", "Difusión antiporter", "Transporte activo", "Difusión simple"],
      correctAnswer: 3,
    },
    {
      id: 33,
      question: "¿Qué es un profármaco?",
      options: [
        "Un fármaco que ha sido retirado del mercado por presentar reacciones adversas severas",
        "Un producto inactivo que se convierte enzimáticamente en un fármaco activo dentro del organismo",
        "Un compuesto de origen natural del que se obtiene uno o más principios activos",
        "Una droga que carece de actividad pero hace sinergia potenciando la acción de otros fármacos",
      ],
      correctAnswer: 1,
    },
    {
      id: 34,
      question: "Señale la opción correcta con respecto a los anestésicos locales:",
      options: [
        "Interactúan directamente con canales operados por ligandos",
        "Las fibras nerviosas en actividad frecuente son más sensibles",
        "El descenso del pH del medio aumenta sus potencias",
        "Las fibras gruesas motoras presentan un bloqueo más rápido y precoz",
      ],
      correctAnswer: 1,
    },
    {
      id: 35,
      question: "¿Por qué los pacientes asmáticos tratados con salbutamol presentan taquiarritmias como efecto adverso?",
      options: [
        "Interacción medicamentosa que interfiere con la acción farmacológica del salbutamol",
        "La hipercapnia generada por el broncoespasmo desencadena taquiarritmia",
        "El aumento de la frecuencia del uso del salbutamol provoca pérdida de selectividad por el subtipo β2",
        "Estos pacientes se insensibilizan frente al uso frecuente del salbutamol",
      ],
      correctAnswer: 2,
    },
    {
      id: 36,
      question: "En un estudio de fase 2 con efectos adversos medidos por escore visual [1] y técnicas bioquímicas [2], seleccione la correcta:",
      options: [
        "Medición directa para [1] y uso de doble ciego para [2]",
        "Uso de ciego para [1] y doble ciego para [2]",
        "Uso de doble ciego para [1] y directa para [2]",
        "Uso de ciego tanto para [1] como para [2]",
      ],
      correctAnswer: 2,
    },
    {
      id: 37,
      question: "La vida media de la atropina es de 4.3 h. Esto quiere decir que es correcto afirmar:",
      options: [
        "Después de una administración única, la concentración decae aproximadamente a D/4 al pasar 4h",
        "El valor numérico del Vd es aproximadamente 5.6 veces el valor de la depuración",
        "Si la absorción intestinal estuviera facilitada, la vida media seguiría siendo la misma",
        "Conociendo la depuración sería imposible estimar el valor del Vd",
      ],
      correctAnswer: 2,
    },
    {
      id: 38,
      question: "La ranitidina tiene un gran volumen de distribución. Este conocimiento permite afirmar que:",
      options: [
        "Al ser similar al volumen plasmático, se concentra en líquido extracelular",
        "Como es mayor que el agua corporal total, se concentra en los tejidos",
        "Al ser mayor que el volumen extracelular, queda confinada en el plasma",
        "Como equivalente al líquido intracelular, ingresa a las células",
      ],
      correctAnswer: 1,
    },
    {
      id: 39,
      question: "Una mujer medicada con benzodiacepinas amamanta a su bebé que comienza a tener compromiso del sensorio. Elija la opción correcta:",
      options: [
        "El bebé tiene inmadurez hepática y no puede metabolizar las drogas de la leche materna",
        "El pH de la leche materna produce aumento de la concentración del fármaco",
        "El bebé debería estar desnutrido para explicar hipoproteinemia",
        "Es poco probable que el compromiso del sensorio esté vinculado a dosis mínimas de la droga",
      ],
      correctAnswer: 0,
    },
    {
      id: 40,
      question: "Un paciente con cáncer tratado con morfina recibe dextropropoxifeno y el dolor aumenta. ¿Qué explica esto?",
      options: [
        "El dextropropoxifeno es un agonista opioide μ parcial",
        "La saturación de los receptores μ provocó una regulación en menos",
        "Ambas drogas compiten por el sistema P450",
        "El dextropropoxifeno no puede actuar debido a la saturación por morfina",
      ],
      correctAnswer: 0,
    },
    {
      id: 41,
      question: "Con respecto a los receptores de la superfamilia esteroide, indique la opción correcta:",
      options: [
        "Se dimerizan para fijarse a los consensos regulatorios del ADN",
        "Tienen localización en la membrana y viajan al núcleo con un transportador",
        "Los que ligan glucocorticoides también ligan somatomedinas 1 y 2",
        "Forman complejos con proteínas como la HSP90",
      ],
      correctAnswer: 3,
    },
    {
      id: 42,
      question: "Investigadores usan manganeso para crear parkinsonismo en ratas. Elija la opción correcta:",
      options: [
        "La toxicidad subaguda sirve para determinar la Dosis Letal 50",
        "La toxicidad crónica dura entre 1 y 6 meses y sirve para estudiar efectos en la progenie",
        "La toxicidad subaguda estudia cuál es el órgano sobre el que impacta la droga a dosis no letales",
        "La toxicidad crónica es inaplicable en este modelo",
      ],
      correctAnswer: 2,
    },
    {
      id: 43,
      question: "De los siguientes efectos de un antagonista de canales de calcio, ¿cuál es el efecto terapéutico?",
      options: ["Relajación del músculo liso arterial", "Vasodilatación", "Bloqueo de los canales lentos de calcio", "Disminución de la tensión arterial"],
      correctAnswer: 3,
    },
    {
      id: 44,
      question: "Indique una ventaja farmacocinética de los análogos de insulina de acción prolongada:",
      options: [
        "Se absorbe desde el tejido subcutáneo de forma más predecible",
        "La duración del efecto no depende de la dosis",
        "La formación de dímeros justifica su mayor duración de efecto",
        "El pico de acción resulta inmediato a su administración",
      ],
      correctAnswer: 0,
    },
    {
      id: 45,
      question: "Un paciente diabético recibe instrucciones para autoadministración de insulina. ¿Qué parámetro farmacocinético se modifica?",
      options: ["El metabolismo", "La eliminación", "La absorción", "La distribución"],
      correctAnswer: 2,
    },
    {
      id: 46,
      question: "Indique el mecanismo de acción de la dapagliflozina:",
      options: [
        "Inhibe selectiva y reversiblemente el cotransportador sodio-glucosa 2 a nivel renal",
        "Reduce la gluconeogénesis y glucogenólisis",
        "Inhibe la enzima dipeptidil-peptidasa 4 (DPP-4)",
        "Bloquea los canales de potasio dependientes de ATP en células beta",
      ],
      correctAnswer: 0,
    },
    {
      id: 47,
      question: "Conociendo el mecanismo de acción de antieméticos, ¿cuál puede presentar parkinsonismo?",
      options: ["Ondansetrón", "Metoclopramida", "Hioscina", "Difenhidramina"],
      correctAnswer: 1,
    },
    {
      id: 48,
      question: "A un paciente con hemorragia digestiva se le administra dextrano de 70 kDa. ¿Cuál es su Vd aparente (en litros)?",
      options: ["5", "4", "28", "42"],
      correctAnswer: 0,
    },
    {
      id: 49,
      question: "¿Cuál sería la fuente más adecuada para buscar información sobre un fármaco nuevo?",
      options: ["El formulario terapéutico nacional (FTN)", "Libro de textos", "Metaanálisis", "Ensayos clínicos"],
      correctAnswer: 2,
    },
    {
      id: 50,
      question: "Ana tiene mutación heterocigota para factor V de Leiden. ¿Ante qué fármacos presenta mayor riesgo de trombosis?",
      options: ["Estatinas", "Estrógenos", "Antiinflamatorios no esteroideos", "Opioides"],
      correctAnswer: 1,
    },
    {
      id: 51,
      question: "Una persona con mutación homocigota recesiva para enzimas metabolizadoras CYP2:",
      options: [
        "Procesa los fármacos en tiempo y forma adecuada",
        "No es capaz de procesar los fármacos",
        "Metaboliza los fármacos de forma ultrarrápida",
        "Incrementa la acción de esta familia de enzimas",
      ],
      correctAnswer: 1,
    },
    {
      id: 52,
      question: "Al seleccionar un medicamento para un anciano, se debe tener en cuenta que:",
      options: [
        "La absorción intestinal suele ser algo más rápida que en adultos",
        "La albúmina plasmática suele estar disminuida, por lo que la fracción libre es menor",
        "Los mecanismos enzimáticos son menos activos, lo que prolonga la semivida",
        "La proporción de masa magra es mayor, aumentando el Vd de fármacos lipofílicos",
      ],
      correctAnswer: 2,
    },
    {
      id: 53,
      question: "Las diferencias en la respuesta a fármacos en niños están determinadas por factores farmacocinéticos, entre ellos:",
      options: [
        "El pH urinario muy básico potencia la excreción de ácidos débiles",
        "La absorción oral suele ser más rápida por las características del peristaltismo",
        "La absorción cutánea es menor debido al espesor de la piel del niño",
        "Existe mayor cantidad de agua en compartimentos corporales y menor fijación a proteínas",
      ],
      correctAnswer: 3,
    },
    {
      id: 54,
      question: "¿Qué fuente de información es más útil para evaluar la seguridad de un analgésico nuevo?",
      options: [
        "Un libro de texto actualizado",
        "Un metaanálisis publicado en Cochrane",
        "Un ensayo clínico controlado de buena calidad",
        "Estudio de casos y controles, y estudio de cohortes",
      ],
      correctAnswer: 3,
    },
    {
      id: 55,
      question: "Un medicamento puede ser retirado del mercado en fase IV porque:",
      options: [
        "La experiencia en el mercado es limitada y eso implica alto riesgo",
        "Carece de ensayos clínicos controlados",
        "La seguridad solo se pudo conocer cuando permaneció mucho tiempo en el mercado",
        "A pesar de ser eficaz y seguro, no cumplió con ser accesible",
      ],
      correctAnswer: 2,
    },
    {
      id: 56,
      question: "¿En qué etapa del estudio de un nuevo medicamento se realizan los ensayos clínicos que documentan su eficacia?",
      options: ["Fase I", "Fase II", "Fase III", "Fase IV"],
      correctAnswer: 2,
    },
    {
      id: 57,
      question: "Para tratar el parkinsonismo por neurolépticos, ¿cuál fármaco emplearía?",
      options: ["L-Dopa", "Trihexifenidilo", "Amantadina", "Selegilina"],
      correctAnswer: 1,
    },
    {
      id: 58,
      question: "Según su mecanismo de acción, ¿cuál fármaco sería mejor para un paciente diabético obeso?",
      options: ["Meglitinidas", "Metformina", "Acarbosa", "Sitagliptina"],
      correctAnswer: 1,
    },
    {
      id: 59,
      question: "Un paciente con tratamiento hipolipemiante refiere mialgias y aumento de CPK. ¿Cuál fármaco sospecharía?",
      options: ["Ácido nicotínico", "Colestiramina", "Ezetimiba", "Atorvastatina"],
      correctAnswer: 3,
    },
    {
      id: 60,
      question: "¿En qué etapa se estudia el fármaco para determinar la mejor vía de administración y máxima dosis tolerada?",
      options: ["Fase I", "Fase II", "Fase III", "Fase IV"],
      correctAnswer: 0,
    },
    {
      id: 61,
      question: "Para revertir el bloqueo neuromuscular con neostigmina, ¿qué bloqueante se empleó en la cirugía?",
      options: ["Succinilcolina", "Diazepam", "Baclofén", "Vecuronio"],
      correctAnswer: 3,
    },
    {
      id: 62,
      question: "El empleo de glucocorticoides en dosis farmacológicas prolongadas puede causar todos los siguientes EXCEPTO:",
      options: ["Susceptibilidad a infecciones", "Desarrollo de hipoglucemia", "Miopatía", "Osteoporosis"],
      correctAnswer: 1,
    },
    {
      id: 63,
      question: "Señale lo verdadero con respecto al sistema nervioso simpático:",
      options: [
        "Es de origen torácico-lumbar",
        "Las fibras nerviosas preganglionares son adrenérgicas",
        "Las fibras nerviosas postganglionares son colinérgicas",
        "Es un sistema anabólico",
      ],
      correctAnswer: 0,
    },
    {
      id: 64,
      question: "En las terminaciones nerviosas adrenérgicas:",
      options: [
        "El precursor de adrenalina es tirosina",
        "Se forma DOPA en la vesícula granulosa",
        "La enzima MAO actúa en la célula post-sináptica",
        "La enzima COMT actúa en terminal nerviosa presináptica",
      ],
      correctAnswer: 0,
    },
    {
      id: 65,
      question: "Señale lo FALSO con respecto al mecanismo de acción de fármacos en el compartimento celular:",
      options: [
        "Los fármacos de nivel 1 se ligan a receptores de neurotransmisores",
        "Los fármacos de nivel 2 modifican la actividad de la proteína G",
        "Los fármacos de nivel 3 modifican la actividad de segundos mensajeros",
        "Adrenalina es un fármaco de nivel 5",
      ],
      correctAnswer: 3,
    },
    {
      id: 66,
      question: "Señale lo verdadero:",
      options: [
        "FENILEFRINA es agonista β adrenérgico",
        "PRAZOSIN es antagonista alfa 1 adrenérgico",
        "YOHIMBINA es agonista alfa 2 adrenérgico",
        "CLONIDINA es agonista beta 2 adrenérgico",
      ],
      correctAnswer: 1,
    },
    {
      id: 67,
      question: "Señale lo FALSO con respecto al receptor beta adrenérgico:",
      options: [
        "Su activación genera broncodilatación",
        "Su activación genera vasodilatación coronaria",
        "Su activación genera vasodilatación periférica",
        "Su activación genera menor secreción de insulina",
      ],
      correctAnswer: 3,
    },
    {
      id: 68,
      question: "Señale lo verdadero:",
      options: [
        "El receptor ionotrópico funciona con segundo mensajero",
        "El receptor alfa 1 adrenérgico es ionotrópico",
        "El receptor beta 1 adrenérgico es ionotrópico",
        "El receptor beta 2 adrenérgico es metabotrópico",
      ],
      correctAnswer: 3,
    },
    {
      id: 69,
      question: "Señale lo verdadero con respecto a los receptores beta adrenérgicos postganglionares:",
      options: [
        "Funcionan con proteína Gs",
        "Son presinápticos",
        "Noradrenalina en bajo nivel interacciona con estos receptores",
        "Su activación aumenta la liberación de noradrenalina",
      ],
      correctAnswer: 0,
    },
    {
      id: 70,
      question: "Señale lo FALSO con respecto a los receptores alfa 2 adrenérgicos postganglionares:",
      options: [
        "Funcionan con proteína Gq",
        "Son presinápticos",
        "Noradrenalina en alto nivel interacciona con estos receptores",
        "Su activación bloquea la liberación de noradrenalina",
      ],
      correctAnswer: 0,
    },
    {
      id: 71,
      question: "Señale lo verdadero con respecto a la acción intracelular de receptores adrenérgicos:",
      options: [
        "El receptor β1 inactiva la proteinquinasa",
        "El receptor β2 funciona con proteína Gi",
        "El receptor alfa 1 activa a la proteinquinasa",
        "El receptor alfa 2 presináptico funciona con proteína Gs",
      ],
      correctAnswer: 2,
    },
    {
      id: 72,
      question: "Señale lo FALSO con respecto a la acción intracelular de los receptores adrenérgicos:",
      options: [
        "En músculo liso bronquial, el receptor β2 activa a la proteinquinasa",
        "En músculo liso bronquial, el receptor β2 activa una proteína funcional",
        "En músculo liso bronquial, la activación del receptor β2 reduce el calcio iónico",
        "En músculo cardíaco, la activación del receptor β1 reduce el calcio iónico",
      ],
      correctAnswer: 3,
    },
    {
      id: 73,
      question: "Señale lo verdadero con respecto a la activación de receptores adrenérgicos:",
      options: [
        "El receptor alfa 1 genera contracción del músculo radial del iris",
        "El receptor β2 genera contracción de arteriolas del músculo esquelético",
        "El receptor β1 genera aumento de la motilidad intestinal",
        "El receptor β1 genera disminución de la secreción de renina",
      ],
      correctAnswer: 0,
    },
    {
      id: 74,
      question: "Señale lo FALSO con respecto a la activación de los siguientes receptores adrenérgicos:",
      options: [
        "El receptor alfa genera contracción del útero",
        "El receptor alfa genera secreción localizada de glándulas sudoríparas",
        "El receptor alfa genera aumento de la secreción de insulina",
        "En glándulas salivales, el receptor alfa genera secreción de agua",
      ],
      correctAnswer: 2,
    },
    {
      id: 75,
      question: "Señale lo FALSO:",
      options: [
        "NORADRENALINA no tiene radical metilo",
        "ADRENALINA se metaboliza en el hígado",
        "DOPAMINA carece de hidroxilo en la cadena lateral",
        "ISOPROTERENOL tiene acciones beta adrenérgicas",
      ],
      correctAnswer: 2,
    },
    {
      id: 76,
      question: "Señale lo verdadero:",
      options: [
        "FENILEFRINA no se administra por vía oral",
        "METOXAMINA tiene acción en sistema nervioso central",
        "METARAMINOL es antagonista alfa adrenérgico",
        "DOBUTAMINA es una catecolamina",
      ],
      correctAnswer: 3,
    },
    {
      id: 77,
      question: "Señale lo FALSO con respecto a ANFETAMINA:",
      options: [
        "Es una fenilamina",
        "En su estructura química posee un núcleo bencénico",
        "Se administra por vía oral",
        "No posee acción simpaticomimética indirecta",
      ],
      correctAnswer: 3,
    },
    {
      id: 78,
      question: "Señale lo FALSO:",
      options: [
        "Los derivados de imidazolina son vasoconstrictores nasales",
        "Los derivados de imidazolina están contraindicados con fármacos IMAO",
        "Los derivados de imidazolina están contraindicados en glaucoma de ángulo cerrado",
        "NAFAZOLINA se administra por vía oral",
      ],
      correctAnswer: 3,
    },
    {
      id: 79,
      question: "Señale lo verdadero con respecto a DOPAMINA:",
      options: [
        "Se usa en el shock cardiogénico",
        "En dosis de 2 mcg/kg/minuto produce vasodilatación renal",
        "En dosis de 10 mcg/kg/minuto produce aumento del VMC",
        "Todo lo anterior es correcto",
      ],
      correctAnswer: 3,
    },
    {
      id: 80,
      question: "Señale lo FALSO con respecto a DOPAMINA:",
      options: [
        "Su vida media es muy breve",
        "Está contraindicada en pacientes tratados con halotano",
        "Está contraindicada en pacientes tratados con fármacos IMAO",
        "Está indicada en pacientes con feocromocitoma",
      ],
      correctAnswer: 3,
    },
    {
      id: 81,
      question: "Señale lo verdadero:",
      options: [
        "DOPAMINA produce vasodilatación",
        "NORADRENALINA está indicada en shock anafiláctico",
        "ISOPROTERENOL genera vasoconstricción",
        "ADRENALINA está contraindicada en pacientes con paro cardíaco",
      ],
      correctAnswer: 1,
    },
    {
      id: 82,
      question: "Señale lo FALSO:",
      options: [
        "FENILEFRINA posee acción simpaticomimética directa",
        "TIRAMINA tiene acción alfa adrenérgica",
        "ISOXSUPRINA genera contracción uterina",
        "EFEDRINA está indicada en pacientes con asma bronquial",
      ],
      correctAnswer: 2,
    },
    {
      id: 83,
      question: "El transporte de sustancias a través de membranas corporales:",
      options: ["Es por difusión simple", "Es por ultrafiltración", "Es por transporte activo", "Todo lo anterior es correcto"],
      correctAnswer: 3,
    },
    {
      id: 84,
      question: "En la difusión simple de sustancias a través de membranas corporales:",
      options: ["La fuente de energía es la hidrólisis de ATP", "Se transporta sustancia hidrosoluble", "No posee selectividad", "Posee competitividad"],
      correctAnswer: 2,
    },
    {
      id: 85,
      question: "Teniendo en cuenta la fórmula del pKa para un ácido:",
      options: [
        "Cuando el pH es menor que el pKa predomina el ácido no ionizado",
        "El numerador es la concentración molecular del ácido ionizado",
        "En medio ácido siempre predomina el ácido no ionizado",
        "Cuando el pH es mayor que el pKa predomina el ácido protonado",
      ],
      correctAnswer: 0,
    },
    {
      id: 86,
      question: "Señale lo verdadero:",
      options: [
        "En sangre las drogas solamente circulan unidas a proteínas plasmáticas",
        "Las drogas hidrosolubles ingresan al SNC por difusión simple",
        "A la biofase llegan las drogas libres en plasma",
        "Todo lo anterior es correcto",
      ],
      correctAnswer: 2,
    },
    {
      id: 87,
      question: "Señale lo correcto con respecto a la interacción del AAS con la ciclooxigenasa:",
      options: ["Es el efecto fisiológico del AAS", "Es el efecto biológico del AAS", "Es el sitio de acción del AAS", "Es el mecanismo de acción del AAS"],
      correctAnswer: 3,
    },
    {
      id: 88,
      question: "Señale lo incorrecto sobre farmacocinética:",
      options: [
        "Se ocupa de la distribución de las drogas",
        "Es independiente de la posología de las drogas",
        "Determina la concentración de una droga en su sitio de acción",
        "Determina la duración de la acción de una droga",
      ],
      correctAnswer: 1,
    },
    {
      id: 89,
      question: "Señale lo FALSO:",
      options: [
        "Para que una droga genere efectos debe llegar a la biofase",
        "En la administración extravascular existe absorción",
        "En la administración intravascular existe absorción para que la droga llegue al plasma",
        "En las drogas hidrosolubles predomina la droga libre en el plasma",
      ],
      correctAnswer: 2,
    },
    {
      id: 90,
      question: "Señale lo verdadero:",
      options: [
        "Las indicaciones de una droga se relacionan especialmente con su farmacocinética",
        "Las contraindicaciones de una droga se relacionan especialmente con la farmacodinamia",
        "La toxicología de una droga se relaciona con su posología",
        "La toxicología de una droga se relaciona con su farmacocinética",
      ],
      correctAnswer: 3,
    },
    {
      id: 91,
      question: "Según el proceso neurofisiológico de la transmisión del dolor, ¿qué fármaco afecta la modulación descendente inhibitoria?",
      options: ["Ibuprofeno", "Tramadol", "Meloxicam", "Prednisona"],
      correctAnswer: 1,
    },
    {
      id: 92,
      question: "¿Cuál es el mecanismo de acción del celecoxib?",
      options: ["Inhibición de COX 1", "Inhibición de COX 2", "Inhibición de COX 3", "Inhibición de fosfolipasa A2"],
      correctAnswer: 1,
    },
    {
      id: 93,
      question: "¿Cuál es el efecto adverso más frecuente de los AINES?",
      options: ["Úlceras gastrointestinales", "Cardiopatías isquémicas", "Depresión respiratoria", "Nefrotoxicidad"],
      correctAnswer: 0,
    },
    {
      id: 94,
      question: "¿A qué denominamos biofase en farmacología?",
      options: [
        "A la fase donde se produce la metabolización de la droga",
        "Espacio biofísico donde se produce la absorción de la droga",
        "Espacio biofísico en que se encuentra la droga con su órgano blanco",
        "A la fase donde se produce la eliminación de la droga",
      ],
      correctAnswer: 2,
    },
    {
      id: 95,
      question: "¿Cuál es el cociente que define el índice terapéutico de un fármaco?",
      options: ["DE50/DL50", "DE99/DL1", "DL50/DE50", "DL1/DE99"],
      correctAnswer: 2,
    },
    {
      id: 96,
      question: "La intoxicación por organofosforado es irreversible por el siguiente motivo:",
      options: ["Agotamiento molecular del receptor", "Taquifilaxia", "Regulación hacia arriba del receptor", "Formación de enlaces covalentes"],
      correctAnswer: 3,
    },
    {
      id: 97,
      question: "¿Cuál de los siguientes opiáceos es un agonista parcial?",
      options: ["Buprenorfina", "Morfina", "Naloxona", "Fentanilo"],
      correctAnswer: 0,
    },
    {
      id: 98,
      question: "¿Cuál es la opción correcta aplicada a formas farmacéuticas endovenosas?",
      options: ["Rápido comienzo de acción", "Gran biodisponibilidad", "Mayor índice terapéutico", "A y B son correctas"],
      correctAnswer: 3,
    },
    {
      id: 99,
      question: "Señale la opción correcta en relación a la potencia de un fármaco:",
      options: [
        "Es más potente cuando requiere dosis menores para producir efecto",
        "Es más potente cuando requiere dosis mayores para producir efecto",
        "No tiene relación con la dosis",
        "Ninguna es correcta",
      ],
      correctAnswer: 0,
    },
    {
      id: 100,
      question: "¿Cuántos dominios transmembrana tiene un receptor ionotrópico de acetilcolina?",
      options: ["4", "5", "6", "7"],
      correctAnswer: 1,
    },
  ],
};
